Fix 2 to 3 issues that cause errors
1)   zip() to list(zip)  for TypeError: len() of unsized object

2)  gridgen_options.iteritems() to iter(gridgen_options.items())  for  'dict' object has no attribute 'iteritems'